server:
  port: 8080
spring:
  application:
      name: qhw
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/myweb?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
      username: root
      password: 1234
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: utf-8
    mode: HTML5
    cache: false
    servlet:
      content-type: text/html
  servlet:
    multipart:
      max-file-size: 5MB
